version: "3.9"

services:
  nest-api:
    container_name: backend-nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - pythia_net

networks:
  pythia_net:
    external: true
