version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: local_pythia_postgres
    restart: always
    environment:
      POSTGRES_USER: pythiauser
      POSTGRES_PASSWORD: pythiapassword
      POSTGRES_DB: pythiadb
    ports:
      - "5432:5432" # Exposes Postgres on localhost:5432
    volumes:
      - postgres_pythia_data:/var/lib/postgresql/data
    networks:
      - pythia_net

volumes:
  postgres_pythia_data: # Defines a named volume for data persistence 

networks:
  pythia_net:
    driver: bridge
    name: pythia_net 