version: '3.9' # Obsolete, can be removed

services:
  frontend:
    container_name: pythia-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3111:3111' # Map host 3111 to container 3111
    environment:
      - PORT=3111 # Tell the app inside to listen on 3111
    env_file:
      - .env # We'll create this next
    networks:
      - pythia_net # Connect to the same network as the backend

networks:
  pythia_net:
    external: true
